version: '3.7'

services:
  database:
    image: "mdillon/postgis:11-alpine"
    environment:
      - POSTGRES_DB=udacity_project
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=udacitydemo
    volumes:
      # persist data even if container shuts down
      - database-data:/var/lib/postgresql/data/
    # open port so host machine can access
    ports:
     - "5432:5432"

  # python:
  #   build: .
  #   depends_on:
  #     - database
  #   command: python script.py

volumes:
  database-data:
