"""003 3NF split city

Revision ID: 03dd58441e73
Revises: befabb0431b5
Create Date: 2020-10-09 22:13:46.068941

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "03dd58441e73"
down_revision = "befabb0431b5"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    # create table States
    op.create_table(
        "states",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )

    # create table Cities
    op.create_table(
        "cities",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=True),
        sa.Column("state_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["state_id"],
            ["states.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )

    # link artist to city
    op.add_column("artists", sa.Column("city_id", sa.Integer(), nullable=False))
    op.create_foreign_key(None, "artists", "cities", ["city_id"], ["id"])

    # link venue to city
    op.add_column("venues", sa.Column("city_id", sa.Integer(), nullable=False))
    op.create_foreign_key(None, "venues", "cities", ["city_id"], ["id"])
    # ### end Alembic commands ###

    # remove redundant columns from artist
    op.drop_column("artists", "city")
    op.drop_column("artists", "state")

    # remove redundant columns from venues
    op.drop_column("venues", "city")
    op.drop_column("venues", "state")


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    # add old columns to venues
    op.add_column(
        "venues",
        sa.Column("city", sa.VARCHAR(length=120), autoincrement=False, nullable=True),
    )
    op.add_column(
        "venues",
        sa.Column("state", sa.VARCHAR(length=120), autoincrement=False, nullable=True),
    )

    # add old columns to artist
    op.add_column(
        "artists",
        sa.Column("city", sa.VARCHAR(length=120), autoincrement=False, nullable=True),
    )
    op.add_column(
        "artists",
        sa.Column("state", sa.VARCHAR(length=120), autoincrement=False, nullable=True),
    )

    # remove link venue to city
    op.drop_constraint(None, "venues", type_="foreignkey")
    op.drop_column("venues", "city_id")

    # remove link artist to city
    op.drop_constraint(None, "artists", type_="foreignkey")
    op.drop_column("artists", "city_id")

    # drop city
    op.drop_table("cities")

    # drop state
    op.drop_table("states")


# ### end Alembic commands ###
