"""002 init shows

Revision ID: 27384078aac6
Revises: 3cc1a4da5daf
Create Date: 2020-10-09 18:14:51.996057

"""
import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = "27384078aac6"
down_revision = "3cc1a4da5daf"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "shows",
        sa.Column("artist_id", sa.Integer(), nullable=False),
        sa.Column("venue_id", sa.Integer(), nullable=False),
        sa.Column("start_time", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["artist_id"],
            ["artists.id"],
        ),
        sa.ForeignKeyConstraint(
            ["venue_id"],
            ["venues.id"],
        ),
        sa.PrimaryKeyConstraint("artist_id", "venue_id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("shows")
    # ### end Alembic commands ###
